export const JWT_PUBLIC_KEY = process.env.JWT_PUBLIC_KEY || `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqc+uexzlRE17cggsMFtJ
V0X2FZbW8rAq3DfFNUVYAzf1BUaYDTX95K46gY5np41qLEeqbbwaD7olPaHauXKL
oC8uvmXSFJHfrzAkf6gAEuXEYN0uuZrabijdUkne1P3E1EVuH8UsdbQQdAUVwyxH
Ivz1qzA2bWbYp56qY6Hif04U0ujik4PaGONSfmc+86n8s+tiFMScvcLfpNU+m+++
zGny6ht+vFpmTCRDeLC4LJpA0UOVxDzw6LAvTWzmQdjADBKaduoFfrSYTMUsMq1R
lghU53owrSzbLgccL8pH1T9d3SbeLrFFQ4DW1dofwQbcgXQJUdOF6pzdEvvwzmRo
kQIDAQAB
-----END PUBLIC KEY-----
`;